### ISSUE TITLE
Future plan of tracking server

### ISSUE THREAD

**Issue by tsaoyu** [WRSC/tracking#43]
My future plan on the server instance current running on Digital Ocean is:

- [x] Doing few tests on @saerdnaer's new Lua tracker script
- [x] Download the SQL database and shutdown the server (15th Sep.)

**Comment by takluyver** [comment]
There are some more changes it would be nice to do to the Lua code (e.g. I'd like to have a go at #42). We can always do this later by running a test server somewhere, but it needs to be accessible on a public IP for the trackers to send data to it, so maybe we should try to do any changes we want before 15th September?

**Comment by tsaoyu** [comment]
@saerdnaer are you interested in working on the tracker's Lua script? Or it is time for me to pick up some Lua (in a positive way 😀 ). @takluyver the main reason why I set a deadline is because there is so little use of the tracking page according to Google Maps API stats. I would like to invest those money on the sailing robot team's domain instead. The firmware feels like now or not-until-next-year thing for me.

**Comment by takluyver** [comment]
Yeah, it makes sense to shut it down soon.

I'm thinking about the tracker development because if we don't do it now, I suspect we'll all forget about it until next year's competition, and there will be 1000 more urgent things to do than tracker firmware, so the trackers will be used with the firmware unchanged.

It's hard to test the trackers properly without a running server for them to send data to. So maybe your plan to shut down the server is actually a useful prompt - whatever changes we want to make (starting with Andy's PR #41) have to be tested before you shut the server down.

The other challenge is that it's impossible to test the trackers without physically having one to test with, so we're relying on you in Southampton to do any testing.

**Comment by saerdnaer** [comment]
@tsaoyu If one of you has questions, I can help you to find answers. But as I know myself, I will hardly find time to continue development myself.
